version: 1
formatters:
  stdFormatter:
    format: '%(asctime)s %(name)s %(levelname)s: %(message)s'
    datefmt: '%d.%m.%Y %H:%M:%S %Z'
handlers:
  fileHandler:
    class: logging.FileHandler
    level: DEBUG
    formatter: stdFormatter
    file: logger.log
  stdoutHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: stdFormatter
    stream: ext://sys.stdout
loggers:
  __main__:
    level: DEBUG
    handlers: [stdoutHandler,fileHandler]
    propagate: no
root:
  level: DEBUG
  handlers: [stdoutHandler,fileHandler]

